/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.examples.localizededitor.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Post service. Represents a row in the &quot;LocalizedEditor_Post&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.examples.localizededitor.model.impl.PostModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.examples.localizededitor.model.impl.PostImpl}.
 * </p>
 *
 * @author adam
 * @see Post
 * @see com.liferay.examples.localizededitor.model.impl.PostImpl
 * @see com.liferay.examples.localizededitor.model.impl.PostModelImpl
 * @generated
 */
public interface PostModel extends BaseModel<Post> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a post model instance should use the {@link Post} interface instead.
	 */

	/**
	 * Returns the primary key of this post.
	 *
	 * @return the primary key of this post
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this post.
	 *
	 * @param primaryKey the primary key of this post
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the post ID of this post.
	 *
	 * @return the post ID of this post
	 */
	public long getPostId();

	/**
	 * Sets the post ID of this post.
	 *
	 * @param postId the post ID of this post
	 */
	public void setPostId(long postId);

	/**
	 * Returns the title of this post.
	 *
	 * @return the title of this post
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this post in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this post
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this post in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this post. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this post in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this post
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this post in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this post
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this post.
	 *
	 * @return the locales and localized titles of this post
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this post.
	 *
	 * @param title the title of this post
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this post in the language.
	 *
	 * @param title the localized title of this post
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this post in the language, and sets the default locale.
	 *
	 * @param title the localized title of this post
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this post from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this post
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this post from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this post
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the content of this post.
	 *
	 * @return the content of this post
	 */
	public String getContent();

	/**
	 * Returns the localized content of this post in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized content of this post
	 */
	@AutoEscape
	public String getContent(Locale locale);

	/**
	 * Returns the localized content of this post in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized content of this post. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getContent(Locale locale, boolean useDefault);

	/**
	 * Returns the localized content of this post in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized content of this post
	 */
	@AutoEscape
	public String getContent(String languageId);

	/**
	 * Returns the localized content of this post in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized content of this post
	 */
	@AutoEscape
	public String getContent(String languageId, boolean useDefault);

	@AutoEscape
	public String getContentCurrentLanguageId();

	@AutoEscape
	public String getContentCurrentValue();

	/**
	 * Returns a map of the locales and localized contents of this post.
	 *
	 * @return the locales and localized contents of this post
	 */
	public Map<Locale, String> getContentMap();

	/**
	 * Sets the content of this post.
	 *
	 * @param content the content of this post
	 */
	public void setContent(String content);

	/**
	 * Sets the localized content of this post in the language.
	 *
	 * @param content the localized content of this post
	 * @param locale the locale of the language
	 */
	public void setContent(String content, Locale locale);

	/**
	 * Sets the localized content of this post in the language, and sets the default locale.
	 *
	 * @param content the localized content of this post
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setContent(String content, Locale locale, Locale defaultLocale);

	public void setContentCurrentLanguageId(String languageId);

	/**
	 * Sets the localized contents of this post from the map of locales and localized contents.
	 *
	 * @param contentMap the locales and localized contents of this post
	 */
	public void setContentMap(Map<Locale, String> contentMap);

	/**
	 * Sets the localized contents of this post from the map of locales and localized contents, and sets the default locale.
	 *
	 * @param contentMap the locales and localized contents of this post
	 * @param defaultLocale the default locale
	 */
	public void setContentMap(Map<Locale, String> contentMap,
		Locale defaultLocale);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(Post post);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Post> toCacheModel();

	@Override
	public Post toEscapedModel();

	@Override
	public Post toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}